### PR TITLE
include responseText when json parse fails

### PR DESCRIPTION
**Pull request by sylspren**

### CODE REVIEW

**Comment by demands** [comment]
This is great; the default JSON parsing error messages are frustratingly obtuse. I wonder if it'd be worth just updating the error message itself, instead of adding the original text to the Error object. Something like: `Error trying to parse JSON response "foo": Unexpected token "o" at position 1.`

...@dannynelson what do you think?

**Comment by serhalp** [comment]
I'm confused about the history here. Wasn't this behavior [added in this PR](https://github.com/goodeggs/json-fetch/pull/8)? Why was it removed?

**Comment by serhalp** [comment]
Oh, it was lost [in this refactor commit](https://github.com/goodeggs/json-fetch/commit/4cdf0ee8d9fac71f9d60b52de7a62ff6247ba2a9#diff-1fdf421c05c1140f6d71444ea2b27638). @dannynelson was that intentional?

**Comment by sylspren** [comment]
hah funny...

great suggestion @dannynelson - udpated!

**Comment by sylspren** [comment]
@demands - i'd prefer leaving it out for ease of error grouping

**Comment by dannynelson** [comment]
👍

**Pull request merged**
